### PR TITLE
Added supersig pallet to Kabocha-0.1.3

### PR DESCRIPTION
**Pull request by gdnathan**

### CODE REVIEW

**Comment by decentration** [comment]
@gdnathan thanks for the PR, just checking... it doesn't look like pallet-supersig is wired up, it has not been added as `impl pallet_supersig...` or added to `construct_runtime!`.

**Comment by decentration** [comment]
forgive me it has, ignore above, was looking at the incorrect branch.

**Comment by decentration** [comment]
@gdnathan could you add comments to describe each impl type for supersig? Like this:

```Rust
impl frame_system::Config for Runtime {
	/// The basic call filter to use in dispatchable.
	type BaseCallFilter = frame_support::traits::Everything;
	/// Block & extrinsics weights: base values and limits.
	type BlockWeights = BlockWeights;
	/// The maximum length of a block (in bytes).
	type BlockLength = BlockLength;
	/// The identifier used to distinguish between accounts.
	type AccountId = AccountId;
	/// The aggregated dispatch type that is available for extrinsics.
...
	```

**Comment by decentration** [comment]
The cargo.toml is still linked to old repo.

https://github.com/gdnathan/kabocha-network-parachain/blob/fcfc237994c8a15e06c37108635815fb7b3bbc9d/runtime/Cargo.toml#L26

**Comment by decentration** [comment]
@gdnathan do we need to add `pallet-supersig/std` to default std features?
https://github.com/gdnathan/kabocha-network-parachain/blob/fcfc237994c8a15e06c37108635815fb7b3bbc9d/runtime/Cargo.toml#L156

**Comment by gdnathan** [comment]
adding pallets will be for 0.1.9, closing this as it is out of date

**Pull request closed without merging**
